"""m6 aio recommendations geo

Revision ID: 1fc3775d868a
Revises: 37bc4d9f65b3
Create Date: 2026-07-13 12:52:38.030339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '1fc3775d868a'
down_revision: Union[str, None] = '37bc4d9f65b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('gap_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', 'dismissed', 'resolved', name='recommendationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_gap_ref'), 'recommendations', ['gap_ref'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_tenant_id'), 'recommendations', ['tenant_id'], unique=False)
    op.add_column('classifications', sa.Column('google_aio_triggered', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('classifications', sa.Column('google_aio_confidence', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('classifications', sa.Column('google_aio_source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='no_aio'))
    op.add_column('classifications', sa.Column('google_aio_signals', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('aio_geo', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'aio_geo')
    op.drop_column('classifications', 'google_aio_signals')
    op.drop_column('classifications', 'google_aio_source_type')
    op.drop_column('classifications', 'google_aio_confidence')
    op.drop_column('classifications', 'google_aio_triggered')
    op.drop_index(op.f('ix_recommendations_tenant_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_gap_ref'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
