"""m5 schedules notify mirror

Revision ID: 37bc4d9f65b3
Revises: 4c6089de2f4c
Create Date: 2026-07-13 03:19:58.030478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '37bc4d9f65b3'
down_revision: Union[str, None] = '4c6089de2f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mirror_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mirror_state_table_name'), 'mirror_state', ['table_name'], unique=True)
    op.create_table('run_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cron_expr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_schedules_next_run_at'), 'run_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_run_schedules_tenant_id'), 'run_schedules', ['tenant_id'], unique=True)
    op.add_column('tenants', sa.Column('notify_emails', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'notify_emails')
    op.drop_index(op.f('ix_run_schedules_tenant_id'), table_name='run_schedules')
    op.drop_index(op.f('ix_run_schedules_next_run_at'), table_name='run_schedules')
    op.drop_table('run_schedules')
    op.drop_index(op.f('ix_mirror_state_table_name'), table_name='mirror_state')
    op.drop_table('mirror_state')
    # ### end Alembic commands ###
