"""m3 mentions classifications visibility variant

Revision ID: 4c6089de2f4c
Revises: 75554afe8807
Create Date: 2026-07-12 23:35:54.060433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '4c6089de2f4c'
down_revision: Union[str, None] = '75554afe8807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('surface', sa.Enum('openai_api', 'chatgpt_web', 'perplexity_web', 'gemini_web', 'google_aio', name='surfacecode'), nullable=False),
    sa.Column('web_search_likelihood', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('classifier_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_query_id'), 'classifications', ['query_id'], unique=False)
    op.create_index(op.f('ix_classifications_tenant_id'), 'classifications', ['tenant_id'], unique=False)
    op.create_table('visibility_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('surface', sa.Enum('openai_api', 'chatgpt_web', 'perplexity_web', 'gemini_web', 'google_aio', name='surfacecode'), nullable=False),
    sa.Column('persona_segment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_score', sa.Float(), nullable=False),
    sa.Column('competitor_scores', sa.JSON(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('scorer_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_daily_date'), 'visibility_daily', ['date'], unique=False)
    op.create_index(op.f('ix_visibility_daily_persona_segment'), 'visibility_daily', ['persona_segment'], unique=False)
    op.create_index(op.f('ix_visibility_daily_tenant_id'), 'visibility_daily', ['tenant_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detector_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentions_entity_type'), 'mentions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_mentions_result_id'), 'mentions', ['result_id'], unique=False)
    op.create_index(op.f('ix_mentions_tenant_id'), 'mentions', ['tenant_id'], unique=False)
    # Postgres needs the enum type created before a column can use it (unlike
    # create_table, add_column does not auto-create it); on SQLite this is a
    # no-op. checkfirst makes re-runs safe.
    resultvariant = sa.Enum('search', 'nosearch', name='resultvariant')
    resultvariant.create(op.get_bind(), checkfirst=True)
    op.add_column('results', sa.Column('variant', resultvariant, nullable=False, server_default='search'))
    op.create_index(op.f('ix_results_variant'), 'results', ['variant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_variant'), table_name='results')
    op.drop_column('results', 'variant')
    sa.Enum(name='resultvariant').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_mentions_tenant_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_result_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_entity_type'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_visibility_daily_tenant_id'), table_name='visibility_daily')
    op.drop_index(op.f('ix_visibility_daily_persona_segment'), table_name='visibility_daily')
    op.drop_index(op.f('ix_visibility_daily_date'), table_name='visibility_daily')
    op.drop_table('visibility_daily')
    op.drop_index(op.f('ix_classifications_tenant_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_query_id'), table_name='classifications')
    op.drop_table('classifications')
    # ### end Alembic commands ###
