"""raw_payloads db storage backend

Revision ID: 730dbcb527fe
Revises: 1fc3775d868a
Create Date: 2026-07-15 02:25:22.172106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '730dbcb527fe'
down_revision: Union[str, None] = '1fc3775d868a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('envelope', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_payloads_uri'), 'raw_payloads', ['uri'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_payloads_uri'), table_name='raw_payloads')
    op.drop_table('raw_payloads')
    # ### end Alembic commands ###
