"use client";

import { useActionState } from "react";
import { generateDraft, type DraftState } from "./actions";

export function GenerateDraft({ factId }: { factId: number }) {
  const [state, action, pending] = useActionState<DraftState, FormData>(
    generateDraft.bind(null, factId),
    null,
  );

  return (
    <div className="mt-3 border-t border-[var(--border)] pt-3">
      <form action={action}>
        <button
          disabled={pending}
          className="rounded-md bg-[var(--accent)] px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
        >
          {pending ? "Drafting…" : "Generate corrective content"}
        </button>
      </form>

      {state && !state.ok && (
        <p className="mt-2 text-xs text-[var(--neg)]">{state.message}</p>
      )}

      {state && state.ok && (
        <div className="mt-3 rounded-md border border-[var(--border)] bg-[var(--inset)] p-3">
          <div className="mb-1 flex items-center gap-2">
            <span className="chip text-[var(--pos)]">draft</span>
            <span className="text-sm font-semibold text-[var(--text)]">
              {state.draft.title}
            </span>
          </div>
          <pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap font-sans text-xs leading-relaxed text-[var(--text-2)]">
            {state.draft.body}
          </pre>
          <p className="mt-2 text-[10px] text-[var(--text-3)]">
            Generated by {state.draft.model} — review before publishing.
          </p>
        </div>
      )}
    </div>
  );
}
