"use client";

import { useActionState } from "react";
import { generateBrief, type BriefState } from "./actions";

export function GenerateBrief({ shardId }: { shardId: number }) {
  const [state, action, pending] = useActionState<BriefState, FormData>(
    generateBrief.bind(null, shardId),
    null,
  );

  return (
    <div>
      <form action={action}>
        <button
          disabled={pending}
          className="btn btn-ghost px-2.5 py-1 text-[11px] disabled:opacity-50"
        >
          {pending ? "Drafting…" : "Generate corrective brief"}
        </button>
      </form>

      {state && !state.ok && <p className="mt-2 text-xs text-[var(--neg)]">{state.message}</p>}

      {state && state.ok && (
        <div className="mt-2 rounded-md border border-[var(--border)] bg-[var(--inset)] p-3">
          <div className="mb-1 flex items-center gap-2">
            <span className="chip text-[var(--pos)]">draft</span>
            <span className="text-sm font-semibold text-[var(--text)]">{state.draft.title}</span>
          </div>
          <pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap font-sans text-xs leading-relaxed text-[var(--text-2)]">
            {state.draft.body}
          </pre>
          <p className="mt-2 text-[10px] text-[var(--text-3)]">
            Draft generated by {state.draft.model}. Review before publishing.
          </p>
        </div>
      )}
    </div>
  );
}
